// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>NPOI.OpenXmlFormats.Encryption</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>True</OrderXMLAttrib><EnableEncoding>True</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace NPOI.OpenXmlFormats.Encryption
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/office/2006/keyEncryptor/password")]
    [System.Xml.Serialization.XmlRootAttribute("encryptedKey", Namespace = "http://schemas.microsoft.com/office/2006/keyEncryptor/password", IsNullable = false)]
    public partial class CT_PasswordKeyEncryptor
    {

        private uint saltSizeField;

        private uint blockSizeField;

        private uint keyBitsField;

        private uint hashSizeField;

        private ST_CipherAlgorithm cipherAlgorithmField;

        private ST_CipherChaining cipherChainingField;

        private ST_HashAlgorithm hashAlgorithmField;

        private byte[] saltValueField;

        private uint spinCountField;

        private byte[] encryptedVerifierHashInputField;

        private byte[] encryptedVerifierHashValueField;

        private byte[] encryptedKeyValueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint saltSize
        {
            get
            {
                return this.saltSizeField;
            }
            set
            {
                this.saltSizeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint blockSize
        {
            get
            {
                return this.blockSizeField;
            }
            set
            {
                this.blockSizeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint keyBits
        {
            get
            {
                return this.keyBitsField;
            }
            set
            {
                this.keyBitsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint hashSize
        {
            get
            {
                return this.hashSizeField;
            }
            set
            {
                this.hashSizeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ST_CipherAlgorithm cipherAlgorithm
        {
            get
            {
                return this.cipherAlgorithmField;
            }
            set
            {
                this.cipherAlgorithmField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ST_CipherChaining cipherChaining
        {
            get
            {
                return this.cipherChainingField;
            }
            set
            {
                this.cipherChainingField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ST_HashAlgorithm hashAlgorithm
        {
            get
            {
                return this.hashAlgorithmField;
            }
            set
            {
                this.hashAlgorithmField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "base64Binary")]
        public byte[] saltValue
        {
            get
            {
                return this.saltValueField;
            }
            set
            {
                this.saltValueField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint spinCount
        {
            get
            {
                return this.spinCountField;
            }
            set
            {
                this.spinCountField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "base64Binary")]
        public byte[] encryptedVerifierHashInput
        {
            get
            {
                return this.encryptedVerifierHashInputField;
            }
            set
            {
                this.encryptedVerifierHashInputField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "base64Binary")]
        public byte[] encryptedVerifierHashValue
        {
            get
            {
                return this.encryptedVerifierHashValueField;
            }
            set
            {
                this.encryptedVerifierHashValueField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "base64Binary")]
        public byte[] encryptedKeyValue
        {
            get
            {
                return this.encryptedKeyValueField;
            }
            set
            {
                this.encryptedKeyValueField = value;
            }
        }

        #region Clone method
        /// <summary>
        /// Create a clone of this CT_PasswordKeyEncryptor object
        /// </summary>
        public virtual CT_PasswordKeyEncryptor Clone()
        {
            return ((CT_PasswordKeyEncryptor)(this.MemberwiseClone()));
        }
        #endregion
    }
}
