// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>NPOI.OpenXmlFormats.Dml.ChartDrawing</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace NPOI.OpenXmlFormats.Dml.ChartDrawing
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_ShapeNonVisual
    {

        private CT_NonVisualDrawingProps cNvPrField;

        private CT_NonVisualDrawingShapeProps cNvSpPrField;

        public CT_ShapeNonVisual()
        {
            this.cNvSpPrField = new CT_NonVisualDrawingShapeProps();
            this.cNvPrField = new CT_NonVisualDrawingProps();
        }

        [XmlElement(Order = 0)]
        public CT_NonVisualDrawingProps cNvPr
        {
            get
            {
                return this.cNvPrField;
            }
            set
            {
                this.cNvPrField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_NonVisualDrawingShapeProps cNvSpPr
        {
            get
            {
                return this.cNvSpPrField;
            }
            set
            {
                this.cNvSpPrField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_Shape
    {

        private CT_ShapeNonVisual nvSpPrField;

        private CT_ShapeProperties spPrField;

        private CT_ShapeStyle styleField;

        private CT_TextBody txBodyField;

        private string macroField;

        private string textlinkField;

        private bool fLocksTextField;

        private bool fPublishedField;

        public CT_Shape()
        {
            this.txBodyField = new CT_TextBody();
            this.styleField = new CT_ShapeStyle();
            this.spPrField = new CT_ShapeProperties();
            this.nvSpPrField = new CT_ShapeNonVisual();
            this.fLocksTextField = true;
            this.fPublishedField = false;
        }

        [XmlElement(Order = 0)]
        public CT_ShapeNonVisual nvSpPr
        {
            get
            {
                return this.nvSpPrField;
            }
            set
            {
                this.nvSpPrField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_ShapeProperties spPr
        {
            get
            {
                return this.spPrField;
            }
            set
            {
                this.spPrField = value;
            }
        }

        [XmlElement(Order = 2)]
        public CT_ShapeStyle style
        {
            get
            {
                return this.styleField;
            }
            set
            {
                this.styleField = value;
            }
        }

        [XmlElement(Order = 3)]
        public CT_TextBody txBody
        {
            get
            {
                return this.txBodyField;
            }
            set
            {
                this.txBodyField = value;
            }
        }

        [XmlAttribute]
        public string macro
        {
            get
            {
                return this.macroField;
            }
            set
            {
                this.macroField = value;
            }
        }

        [XmlAttribute]
        public string textlink
        {
            get
            {
                return this.textlinkField;
            }
            set
            {
                this.textlinkField = value;
            }
        }

        [XmlAttribute]
        [DefaultValue(true)]
        public bool fLocksText
        {
            get
            {
                return this.fLocksTextField;
            }
            set
            {
                this.fLocksTextField = value;
            }
        }

        [XmlAttribute]
        [DefaultValue(false)]
        public bool fPublished
        {
            get
            {
                return this.fPublishedField;
            }
            set
            {
                this.fPublishedField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_ConnectorNonVisual
    {

        private CT_NonVisualDrawingProps cNvPrField;

        private CT_NonVisualConnectorProperties cNvCxnSpPrField;

        public CT_ConnectorNonVisual()
        {
            this.cNvCxnSpPrField = new CT_NonVisualConnectorProperties();
        }

        [XmlElement(Order = 0)]
        public CT_NonVisualDrawingProps cNvPr
        {
            get
            {
                return this.cNvPrField;
            }
            set
            {
                this.cNvPrField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_NonVisualConnectorProperties cNvCxnSpPr
        {
            get
            {
                return this.cNvCxnSpPrField;
            }
            set
            {
                this.cNvCxnSpPrField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_Connector
    {

        private CT_ConnectorNonVisual nvCxnSpPrField;

        private CT_ShapeProperties spPrField;

        private CT_ShapeStyle styleField;

        private string macroField;

        private bool fPublishedField;

        public CT_Connector()
        {
            this.nvCxnSpPrField = new CT_ConnectorNonVisual();
            this.fPublishedField = false;
        }

        [XmlElement(Order = 0)]
        public CT_ConnectorNonVisual nvCxnSpPr
        {
            get
            {
                return this.nvCxnSpPrField;
            }
            set
            {
                this.nvCxnSpPrField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_ShapeProperties spPr
        {
            get
            {
                return this.spPrField;
            }
            set
            {
                this.spPrField = value;
            }
        }

        [XmlElement(Order = 2)]
        public CT_ShapeStyle style
        {
            get
            {
                return this.styleField;
            }
            set
            {
                this.styleField = value;
            }
        }

        [XmlAttribute]
        public string macro
        {
            get
            {
                return this.macroField;
            }
            set
            {
                this.macroField = value;
            }
        }

        [XmlAttribute]
        [DefaultValue(false)]
        public bool fPublished
        {
            get
            {
                return this.fPublishedField;
            }
            set
            {
                this.fPublishedField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_PictureNonVisual
    {

        private CT_NonVisualDrawingProps cNvPrField;

        private CT_NonVisualPictureProperties cNvPicPrField;

        public CT_PictureNonVisual()
        {
            this.cNvPicPrField = new CT_NonVisualPictureProperties();
        }

        [XmlElement(Order = 0)]
        public CT_NonVisualDrawingProps cNvPr
        {
            get
            {
                return this.cNvPrField;
            }
            set
            {
                this.cNvPrField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_NonVisualPictureProperties cNvPicPr
        {
            get
            {
                return this.cNvPicPrField;
            }
            set
            {
                this.cNvPicPrField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_Picture
    {

        private CT_PictureNonVisual nvPicPrField;

        private CT_BlipFillProperties blipFillField;

        private CT_ShapeProperties spPrField;

        private CT_ShapeStyle styleField;

        private string macroField;

        private bool fPublishedField;

        public CT_Picture()
        {
            this.blipFillField = new CT_BlipFillProperties();
            this.nvPicPrField = new CT_PictureNonVisual();
            this.macroField = "";
            this.fPublishedField = false;
        }

        [XmlElement(Order = 0)]
        public CT_PictureNonVisual nvPicPr
        {
            get
            {
                return this.nvPicPrField;
            }
            set
            {
                this.nvPicPrField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_BlipFillProperties blipFill
        {
            get
            {
                return this.blipFillField;
            }
            set
            {
                this.blipFillField = value;
            }
        }

        [XmlElement(Order = 2)]
        public CT_ShapeProperties spPr
        {
            get
            {
                return this.spPrField;
            }
            set
            {
                this.spPrField = value;
            }
        }

        [XmlElement(Order = 3)]
        public CT_ShapeStyle style
        {
            get
            {
                return this.styleField;
            }
            set
            {
                this.styleField = value;
            }
        }

        [XmlAttribute]
        [DefaultValue("")]
        public string macro
        {
            get
            {
                return this.macroField;
            }
            set
            {
                this.macroField = value;
            }
        }

        [XmlAttribute]
        [DefaultValue(false)]
        public bool fPublished
        {
            get
            {
                return this.fPublishedField;
            }
            set
            {
                this.fPublishedField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_GraphicFrameNonVisual
    {

        private CT_NonVisualDrawingProps cNvPrField;

        private CT_NonVisualGraphicFrameProperties cNvGraphicFramePrField;

        public CT_GraphicFrameNonVisual()
        {
            this.cNvGraphicFramePrField = new CT_NonVisualGraphicFrameProperties();
        }

        [XmlElement(Order = 0)]
        public CT_NonVisualDrawingProps cNvPr
        {
            get
            {
                return this.cNvPrField;
            }
            set
            {
                this.cNvPrField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_NonVisualGraphicFrameProperties cNvGraphicFramePr
        {
            get
            {
                return this.cNvGraphicFramePrField;
            }
            set
            {
                this.cNvGraphicFramePrField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_GraphicFrame
    {

        private CT_GraphicFrameNonVisual nvGraphicFramePrField;

        private CT_Transform2D xfrmField;

        private CT_GraphicalObject graphicField;

        private string macroField;

        private bool fPublishedField;

        public CT_GraphicFrame()
        {
            this.graphicField = new CT_GraphicalObject();
            this.nvGraphicFramePrField = new CT_GraphicFrameNonVisual();
            this.fPublishedField = false;
        }

        [XmlElement(Order = 0)]
        public CT_GraphicFrameNonVisual nvGraphicFramePr
        {
            get
            {
                return this.nvGraphicFramePrField;
            }
            set
            {
                this.nvGraphicFramePrField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_Transform2D xfrm
        {
            get
            {
                return this.xfrmField;
            }
            set
            {
                this.xfrmField = value;
            }
        }

        [XmlElement(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/main", Order = 2)]
        public CT_GraphicalObject graphic
        {
            get
            {
                return this.graphicField;
            }
            set
            {
                this.graphicField = value;
            }
        }

        [XmlAttribute]
        public string macro
        {
            get
            {
                return this.macroField;
            }
            set
            {
                this.macroField = value;
            }
        }

        [XmlAttribute]
        [DefaultValue(false)]
        public bool fPublished
        {
            get
            {
                return this.fPublishedField;
            }
            set
            {
                this.fPublishedField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_GroupShapeNonVisual
    {

        private CT_NonVisualDrawingProps cNvPrField;

        private CT_NonVisualGroupDrawingShapeProps cNvGrpSpPrField;

        public CT_GroupShapeNonVisual()
        {
            this.cNvGrpSpPrField = new CT_NonVisualGroupDrawingShapeProps();
        }

        [XmlElement(Order = 0)]
        public CT_NonVisualDrawingProps cNvPr
        {
            get
            {
                return this.cNvPrField;
            }
            set
            {
                this.cNvPrField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_NonVisualGroupDrawingShapeProps cNvGrpSpPr
        {
            get
            {
                return this.cNvGrpSpPrField;
            }
            set
            {
                this.cNvGrpSpPrField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_GroupShape
    {

        private CT_GroupShapeNonVisual nvGrpSpPrField;

        private CT_GroupShapeProperties grpSpPrField;

        private List<object> itemsField;

        public CT_GroupShape()
        {
            this.itemsField = new List<object>();
            this.grpSpPrField = new CT_GroupShapeProperties();
            this.nvGrpSpPrField = new CT_GroupShapeNonVisual();
        }

        [XmlElement(Order = 0)]
        public CT_GroupShapeNonVisual nvGrpSpPr
        {
            get
            {
                return this.nvGrpSpPrField;
            }
            set
            {
                this.nvGrpSpPrField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_GroupShapeProperties grpSpPr
        {
            get
            {
                return this.grpSpPrField;
            }
            set
            {
                this.grpSpPrField = value;
            }
        }

        [XmlElement("cxnSp", typeof(CT_Connector), Order = 2)]
        [XmlElement("graphicFrame", typeof(CT_GraphicFrame), Order = 2)]
        [XmlElement("grpSp", typeof(CT_GroupShape), Order = 2)]
        [XmlElement("pic", typeof(CT_Picture), Order = 2)]
        [XmlElement("sp", typeof(CT_Shape), Order = 2)]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_Marker
    {

        private double xField;

        private double yField;

        [XmlElement(Order = 0)]
        public double x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        [XmlElement(Order = 1)]
        public double y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_RelSizeAnchor
    {

        private CT_Marker fromField;

        private CT_Marker toField;

        private object itemField;

        public CT_RelSizeAnchor()
        {
            this.toField = new CT_Marker();
            this.fromField = new CT_Marker();
        }

        [XmlElement(Order = 0)]
        public CT_Marker from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_Marker to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        [XmlElement("cxnSp", typeof(CT_Connector), Order = 2)]
        [XmlElement("graphicFrame", typeof(CT_GraphicFrame), Order = 2)]
        [XmlElement("grpSp", typeof(CT_GroupShape), Order = 2)]
        [XmlElement("pic", typeof(CT_Picture), Order = 2)]
        [XmlElement("sp", typeof(CT_Shape), Order = 2)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_AbsSizeAnchor
    {

        private CT_Marker fromField;

        private CT_PositiveSize2D extField;

        private object itemField;

        public CT_AbsSizeAnchor()
        {
            this.fromField = new CT_Marker();
        }

        [XmlElement(Order = 0)]
        public CT_Marker from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        [XmlElement(Order = 1)]
        public CT_PositiveSize2D ext
        {
            get
            {
                return this.extField;
            }
            set
            {
                this.extField = value;
            }
        }

        [XmlElement("cxnSp", typeof(CT_Connector), Order = 2)]
        [XmlElement("graphicFrame", typeof(CT_GraphicFrame), Order = 2)]
        [XmlElement("grpSp", typeof(CT_GroupShape), Order = 2)]
        [XmlElement("pic", typeof(CT_Picture), Order = 2)]
        [XmlElement("sp", typeof(CT_Shape), Order = 2)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing", IsNullable = true)]
    public class CT_Drawing
    {

        private List<object> itemsField;

        public CT_Drawing()
        {
            this.itemsField = new List<object>();
        }

        [XmlElement("absSizeAnchor", typeof(CT_AbsSizeAnchor), Order = 0)]
        [XmlElement("relSizeAnchor", typeof(CT_RelSizeAnchor), Order = 0)]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}
