// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>NPOI.OpenXmlFormats</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace NPOI.OpenXmlFormats.Dml
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    
    [System.SerializableAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    [System.Xml.Serialization.XmlRootAttribute("inline", Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing", IsNullable = false)]
    public partial class CT_Inline
    {

        private CT_PositiveSize2D extentField;

        private CT_EffectExtent effectExtentField;

        private CT_NonVisualDrawingProps docPrField;

        private CT_NonVisualGraphicFrameProperties cNvGraphicFramePrField;

        private CT_GraphicalObject graphicField;

        private uint distTField;

        private bool distTFieldSpecified;

        private uint distBField;

        private bool distBFieldSpecified;

        private uint distLField;

        private bool distLFieldSpecified;

        private uint distRField;

        private bool distRFieldSpecified;

        /// <summary>
        /// CT_Inline class constructor
        /// </summary>
        public CT_Inline()
        {
            this.graphicField = new CT_GraphicalObject();
            this.cNvGraphicFramePrField = new CT_NonVisualGraphicFrameProperties();
            this.docPrField = new CT_NonVisualDrawingProps();
            this.effectExtentField = new CT_EffectExtent();
            this.extentField = new CT_PositiveSize2D();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CT_PositiveSize2D extent
        {
            get
            {
                return this.extentField;
            }
            set
            {
                this.extentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public CT_EffectExtent effectExtent
        {
            get
            {
                return this.effectExtentField;
            }
            set
            {
                this.effectExtentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public CT_NonVisualDrawingProps docPr
        {
            get
            {
                return this.docPrField;
            }
            set
            {
                this.docPrField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public CT_NonVisualGraphicFrameProperties cNvGraphicFramePr
        {
            get
            {
                return this.cNvGraphicFramePrField;
            }
            set
            {
                this.cNvGraphicFramePrField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/main", Order = 4)]
        public CT_GraphicalObject graphic
        {
            get
            {
                return this.graphicField;
            }
            set
            {
                this.graphicField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distT
        {
            get
            {
                return this.distTField;
            }
            set
            {
                this.distTField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distTSpecified
        {
            get
            {
                return this.distTFieldSpecified;
            }
            set
            {
                this.distTFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distB
        {
            get
            {
                return this.distBField;
            }
            set
            {
                this.distBField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distBSpecified
        {
            get
            {
                return this.distBFieldSpecified;
            }
            set
            {
                this.distBFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distL
        {
            get
            {
                return this.distLField;
            }
            set
            {
                this.distLField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distLSpecified
        {
            get
            {
                return this.distLFieldSpecified;
            }
            set
            {
                this.distLFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distR
        {
            get
            {
                return this.distRField;
            }
            set
            {
                this.distRField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distRSpecified
        {
            get
            {
                return this.distRFieldSpecified;
            }
            set
            {
                this.distRFieldSpecified = value;
            }
        }

        public CT_PositiveSize2D AddNewExtent()
        {
            if (this.extentField == null)
                this.extentField = new CT_PositiveSize2D();
            return this.extentField;
        }

        public CT_NonVisualDrawingProps AddNewDocPr()
        {
            if (this.docPrField == null)
                this.docPrField = new CT_NonVisualDrawingProps();
            return this.docPrField;
        }
    }

    
    [System.SerializableAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing", IsNullable = true)]
    public partial class CT_EffectExtent
    {

        private long lField;

        private long tField;

        private long rField;

        private long bField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long l
        {
            get
            {
                return this.lField;
            }
            set
            {
                this.lField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long t
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long r
        {
            get
            {
                return this.rField;
            }
            set
            {
                this.rField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long b
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }
    }

    
    [System.SerializableAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    [System.Xml.Serialization.XmlRootAttribute("anchor", Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing", IsNullable = false)]
    public partial class CT_Anchor
    {

        private CT_Point2D simplePosField;

        private CT_PosH positionHField;

        private CT_PosV positionVField;

        private CT_PositiveSize2D extentField;

        private CT_EffectExtent effectExtentField;

        private object itemField;

        private CT_NonVisualDrawingProps docPrField;

        private CT_NonVisualGraphicFrameProperties cNvGraphicFramePrField;

        private CT_GraphicalObject graphicField;

        private uint distTField;

        private bool distTFieldSpecified;

        private uint distBField;

        private bool distBFieldSpecified;

        private uint distLField;

        private bool distLFieldSpecified;

        private uint distRField;

        private bool distRFieldSpecified;

        private bool simplePos1Field;

        private bool simplePos1FieldSpecified;

        private uint relativeHeightField;

        private bool behindDocField;

        private bool lockedField;

        private bool layoutInCellField;

        private bool hiddenField;

        private bool hiddenFieldSpecified;

        private bool allowOverlapField;

        /// <summary>
        /// CT_Anchor class constructor
        /// </summary>
        public CT_Anchor()
        {
            this.effectExtentField = new CT_EffectExtent();
            this.positionVField = new CT_PosV();
            this.positionHField = new CT_PosH();
            this.simplePosField = new CT_Point2D();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CT_Point2D simplePos
        {
            get
            {
                return this.simplePosField;
            }
            set
            {
                this.simplePosField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public CT_PosH positionH
        {
            get
            {
                return this.positionHField;
            }
            set
            {
                this.positionHField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public CT_PosV positionV
        {
            get
            {
                return this.positionVField;
            }
            set
            {
                this.positionVField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public CT_PositiveSize2D extent
        {
            get
            {
                return this.extentField;
            }
            set
            {
                this.extentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public CT_EffectExtent effectExtent
        {
            get
            {
                return this.effectExtentField;
            }
            set
            {
                this.effectExtentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("wrapNone", typeof(CT_WrapNone), Order = 5)]
        [System.Xml.Serialization.XmlElementAttribute("wrapSquare", typeof(CT_WrapSquare), Order = 5)]
        [System.Xml.Serialization.XmlElementAttribute("wrapThrough", typeof(CT_WrapThrough), Order = 5)]
        [System.Xml.Serialization.XmlElementAttribute("wrapTight", typeof(CT_WrapTight), Order = 5)]
        [System.Xml.Serialization.XmlElementAttribute("wrapTopAndBottom", typeof(CT_WrapTopBottom), Order = 5)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public CT_NonVisualDrawingProps docPr
        {
            get
            {
                return this.docPrField;
            }
            set
            {
                this.docPrField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public CT_NonVisualGraphicFrameProperties cNvGraphicFramePr
        {
            get
            {
                return this.cNvGraphicFramePrField;
            }
            set
            {
                this.cNvGraphicFramePrField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/main", Order = 8)]
        public CT_GraphicalObject graphic
        {
            get
            {
                return this.graphicField;
            }
            set
            {
                this.graphicField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distT
        {
            get
            {
                return this.distTField;
            }
            set
            {
                this.distTField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distTSpecified
        {
            get
            {
                return this.distTFieldSpecified;
            }
            set
            {
                this.distTFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distB
        {
            get
            {
                return this.distBField;
            }
            set
            {
                this.distBField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distBSpecified
        {
            get
            {
                return this.distBFieldSpecified;
            }
            set
            {
                this.distBFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distL
        {
            get
            {
                return this.distLField;
            }
            set
            {
                this.distLField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distLSpecified
        {
            get
            {
                return this.distLFieldSpecified;
            }
            set
            {
                this.distLFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distR
        {
            get
            {
                return this.distRField;
            }
            set
            {
                this.distRField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distRSpecified
        {
            get
            {
                return this.distRFieldSpecified;
            }
            set
            {
                this.distRFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("simplePos")]
        public bool simplePos1
        {
            get
            {
                return this.simplePos1Field;
            }
            set
            {
                this.simplePos1Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool simplePos1Specified
        {
            get
            {
                return this.simplePos1FieldSpecified;
            }
            set
            {
                this.simplePos1FieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint relativeHeight
        {
            get
            {
                return this.relativeHeightField;
            }
            set
            {
                this.relativeHeightField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool behindDoc
        {
            get
            {
                return this.behindDocField;
            }
            set
            {
                this.behindDocField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool locked
        {
            get
            {
                return this.lockedField;
            }
            set
            {
                this.lockedField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool layoutInCell
        {
            get
            {
                return this.layoutInCellField;
            }
            set
            {
                this.layoutInCellField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hiddenSpecified
        {
            get
            {
                return this.hiddenFieldSpecified;
            }
            set
            {
                this.hiddenFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool allowOverlap
        {
            get
            {
                return this.allowOverlapField;
            }
            set
            {
                this.allowOverlapField = value;
            }
        }
    }

    
    [System.SerializableAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing", IsNullable = true)]
    public partial class CT_PosH
    {

        private object itemField;

        private ST_RelFromH relativeFromField;

        [System.Xml.Serialization.XmlElementAttribute("align", typeof(ST_AlignH), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("posOffset", typeof(int), Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ST_RelFromH relativeFrom
        {
            get
            {
                return this.relativeFromField;
            }
            set
            {
                this.relativeFromField = value;
            }
        }
    }

    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    public enum ST_AlignH
    {

        /// <remarks/>
        left,

        /// <remarks/>
        right,

        /// <remarks/>
        center,

        /// <remarks/>
        inside,

        /// <remarks/>
        outside,
    }

    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    public enum ST_RelFromH
    {

        /// <remarks/>
        margin,

        /// <remarks/>
        page,

        /// <remarks/>
        column,

        /// <remarks/>
        character,

        /// <remarks/>
        leftMargin,

        /// <remarks/>
        rightMargin,

        /// <remarks/>
        insideMargin,

        /// <remarks/>
        outsideMargin,
    }

    
    [System.SerializableAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing", IsNullable = true)]
    public partial class CT_PosV
    {

        private object itemField;

        private ST_RelFromV relativeFromField;

        [System.Xml.Serialization.XmlElementAttribute("align", typeof(ST_AlignV), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("posOffset", typeof(int), Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ST_RelFromV relativeFrom
        {
            get
            {
                return this.relativeFromField;
            }
            set
            {
                this.relativeFromField = value;
            }
        }
    }

    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    public enum ST_AlignV
    {

        /// <remarks/>
        top,

        /// <remarks/>
        bottom,

        /// <remarks/>
        center,

        /// <remarks/>
        inside,

        /// <remarks/>
        outside,
    }

    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    public enum ST_RelFromV
    {

        /// <remarks/>
        margin,

        /// <remarks/>
        page,

        /// <remarks/>
        paragraph,

        /// <remarks/>
        line,

        /// <remarks/>
        topMargin,

        /// <remarks/>
        bottomMargin,

        /// <remarks/>
        insideMargin,

        /// <remarks/>
        outsideMargin,
    }

    
    [System.SerializableAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing", IsNullable = true)]
    public partial class CT_WrapNone
    {
    }

    
    [System.SerializableAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing", IsNullable = true)]
    public partial class CT_WrapSquare
    {

        private CT_EffectExtent effectExtentField;

        private ST_WrapText wrapTextField;

        private uint distTField;

        private bool distTFieldSpecified;

        private uint distBField;

        private bool distBFieldSpecified;

        private uint distLField;

        private bool distLFieldSpecified;

        private uint distRField;

        private bool distRFieldSpecified;

        /// <summary>
        /// CT_WrapSquare class constructor
        /// </summary>
        public CT_WrapSquare()
        {
            this.effectExtentField = new CT_EffectExtent();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CT_EffectExtent effectExtent
        {
            get
            {
                return this.effectExtentField;
            }
            set
            {
                this.effectExtentField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ST_WrapText wrapText
        {
            get
            {
                return this.wrapTextField;
            }
            set
            {
                this.wrapTextField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distT
        {
            get
            {
                return this.distTField;
            }
            set
            {
                this.distTField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distTSpecified
        {
            get
            {
                return this.distTFieldSpecified;
            }
            set
            {
                this.distTFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distB
        {
            get
            {
                return this.distBField;
            }
            set
            {
                this.distBField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distBSpecified
        {
            get
            {
                return this.distBFieldSpecified;
            }
            set
            {
                this.distBFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distL
        {
            get
            {
                return this.distLField;
            }
            set
            {
                this.distLField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distLSpecified
        {
            get
            {
                return this.distLFieldSpecified;
            }
            set
            {
                this.distLFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distR
        {
            get
            {
                return this.distRField;
            }
            set
            {
                this.distRField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distRSpecified
        {
            get
            {
                return this.distRFieldSpecified;
            }
            set
            {
                this.distRFieldSpecified = value;
            }
        }
    }

    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    public enum ST_WrapText
    {

        /// <remarks/>
        bothSides,

        /// <remarks/>
        left,

        /// <remarks/>
        right,

        /// <remarks/>
        largest,
    }

    
    [System.SerializableAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing", IsNullable = true)]
    public partial class CT_WrapThrough
    {

        private CT_WrapPath wrapPolygonField;

        private ST_WrapText wrapTextField;

        private uint distLField;

        private bool distLFieldSpecified;

        private uint distRField;

        private bool distRFieldSpecified;

        /// <summary>
        /// CT_WrapThrough class constructor
        /// </summary>
        public CT_WrapThrough()
        {
            this.wrapPolygonField = new CT_WrapPath();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CT_WrapPath wrapPolygon
        {
            get
            {
                return this.wrapPolygonField;
            }
            set
            {
                this.wrapPolygonField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ST_WrapText wrapText
        {
            get
            {
                return this.wrapTextField;
            }
            set
            {
                this.wrapTextField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distL
        {
            get
            {
                return this.distLField;
            }
            set
            {
                this.distLField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distLSpecified
        {
            get
            {
                return this.distLFieldSpecified;
            }
            set
            {
                this.distLFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distR
        {
            get
            {
                return this.distRField;
            }
            set
            {
                this.distRField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distRSpecified
        {
            get
            {
                return this.distRFieldSpecified;
            }
            set
            {
                this.distRFieldSpecified = value;
            }
        }
    }

    
    [System.SerializableAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing", IsNullable = true)]
    public partial class CT_WrapPath
    {

        private CT_Point2D startField;

        private List<CT_Point2D> lineToField;

        private bool editedField;

        private bool editedFieldSpecified;

        /// <summary>
        /// CT_WrapPath class constructor
        /// </summary>
        public CT_WrapPath()
        {
            this.lineToField = new List<CT_Point2D>();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CT_Point2D start
        {
            get
            {
                return this.startField;
            }
            set
            {
                this.startField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("lineTo", Order = 1)]
        public List<CT_Point2D> lineTo
        {
            get
            {
                return this.lineToField;
            }
            set
            {
                this.lineToField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool edited
        {
            get
            {
                return this.editedField;
            }
            set
            {
                this.editedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool editedSpecified
        {
            get
            {
                return this.editedFieldSpecified;
            }
            set
            {
                this.editedFieldSpecified = value;
            }
        }
    }

    
    [System.SerializableAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing", IsNullable = true)]
    public partial class CT_WrapTight
    {

        private CT_WrapPath wrapPolygonField;

        private ST_WrapText wrapTextField;

        private uint distLField;

        private bool distLFieldSpecified;

        private uint distRField;

        private bool distRFieldSpecified;

        /// <summary>
        /// CT_WrapTight class constructor
        /// </summary>
        public CT_WrapTight()
        {
            this.wrapPolygonField = new CT_WrapPath();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CT_WrapPath wrapPolygon
        {
            get
            {
                return this.wrapPolygonField;
            }
            set
            {
                this.wrapPolygonField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ST_WrapText wrapText
        {
            get
            {
                return this.wrapTextField;
            }
            set
            {
                this.wrapTextField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distL
        {
            get
            {
                return this.distLField;
            }
            set
            {
                this.distLField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distLSpecified
        {
            get
            {
                return this.distLFieldSpecified;
            }
            set
            {
                this.distLFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distR
        {
            get
            {
                return this.distRField;
            }
            set
            {
                this.distRField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distRSpecified
        {
            get
            {
                return this.distRFieldSpecified;
            }
            set
            {
                this.distRFieldSpecified = value;
            }
        }
    }

    
    [System.SerializableAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing", IsNullable = true)]
    public partial class CT_WrapTopBottom
    {

        private CT_EffectExtent effectExtentField;

        private uint distTField;

        private bool distTFieldSpecified;

        private uint distBField;

        private bool distBFieldSpecified;

        /// <summary>
        /// CT_WrapTopBottom class constructor
        /// </summary>
        public CT_WrapTopBottom()
        {
            this.effectExtentField = new CT_EffectExtent();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CT_EffectExtent effectExtent
        {
            get
            {
                return this.effectExtentField;
            }
            set
            {
                this.effectExtentField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distT
        {
            get
            {
                return this.distTField;
            }
            set
            {
                this.distTField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distTSpecified
        {
            get
            {
                return this.distTFieldSpecified;
            }
            set
            {
                this.distTFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint distB
        {
            get
            {
                return this.distBField;
            }
            set
            {
                this.distBField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distBSpecified
        {
            get
            {
                return this.distBFieldSpecified;
            }
            set
            {
                this.distBFieldSpecified = value;
            }
        }
    }
}
