// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>schemas</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;
using System;

namespace NPOI.OpenXmlFormats
{

    [Serializable]
    [System.Diagnostics.DebuggerStepThrough]
    [System.ComponentModel.DesignerCategory("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]
    public class CT_Variant
    {

        //private object itemField;

        //private ItemChoiceType itemElementNameField;
        //[XmlElement("array", typeof(CT_Array))]
        //[XmlElement("blob", typeof(byte[]), DataType = "base64Binary")]
        //[XmlElement("bool", typeof(bool))]
        //[XmlElement("bstr", typeof(string))]
        //[XmlElement("cf", typeof(CT_Cf))]
        //[XmlElement("clsid", typeof(string))]
        //[XmlElement("cy", typeof(string))]
        //[XmlElement("date", typeof(System.DateTime))]
        //[XmlElement("decimal", typeof(decimal))]
        //[XmlElement("empty", typeof(CT_Empty))]
        //[XmlElement("error", typeof(string))]
        //[XmlElement("filetime", typeof(System.DateTime))]
        //[XmlElement("int", typeof(int))]
        //[XmlElement("null", typeof(CT_Null))]
        //[XmlElement("oblob", typeof(byte[]), DataType = "base64Binary")]
        //[XmlElement("ostorage", typeof(byte[]), DataType = "base64Binary")]
        //[XmlElement("ostream", typeof(byte[]), DataType = "base64Binary")]
        //[XmlElement("storage", typeof(byte[]), DataType = "base64Binary")]
        //[XmlElement("stream", typeof(byte[]), DataType = "base64Binary")]
        //[XmlElement("ui1", typeof(byte))]
        //[XmlElement("ui2", typeof(ushort))]
        //[XmlElement("ui4", typeof(uint))]
        //[XmlElement("ui8", typeof(ulong))]
        //[XmlElement("uint", typeof(uint))]
        ////[XmlElement("variant", typeof(CT_Variant))]
        //[XmlElement("vector", typeof(CT_Vector))]
        //[XmlElement("vstream", typeof(CT_Vstream))]
        //[XmlChoiceIdentifier("ItemElementName")]
        //public object Item
        //{
        //    get
        //    {
        //        return this.itemField;
        //    }
        //    set
        //    {
        //        this.itemField = value;
        //    }
        //}

        //[XmlIgnore]
        //public ItemChoiceType ItemElementName
        //{
        //    get
        //    {
        //        return this.itemElementNameField;
        //    }
        //    set
        //    {
        //        this.itemElementNameField = value;
        //    }
        //}
        private sbyte i1Field = 0;
        private bool i1SpecifiedField = false;
        private short i2Field = 0;
        private bool i2SpecifiedField = false;
        private int i4Field = 0;
        private bool i4SpecifiedField = false;
        private long i8Field = 0;
        private bool i8SpecifiedField = false;
        //[XmlElement]
        //public sbyte i1
        //{
        //    get { return i1Field; }
        //    set { i1Field = value; }
        //}
        //[XmlIgnore]
        //public bool i1Specified
        //{
        //    get { return i1SpecifiedField; }
        //    set { i1SpecifiedField = value; }
        //}
        [XmlElement]
        public short i2
        {
            get { return i2Field; }
            set { i2Field = value; }
        }
        [XmlIgnore]
        public bool i2Specified
        {
            get { return i2SpecifiedField; }
            set { i2SpecifiedField = value; }
        }
        [XmlElement]
        public int i4
        {
            get { return i4Field; }
            set { i4Field = value; }
        }
        [XmlIgnore]
        public bool i4Specified
        {
            get { return i4SpecifiedField; }
            set { i4SpecifiedField = value; }
        }
        [XmlElement]
        public long i8
        {
            get { return i8Field; }
            set { i8Field = value; }
        }
        [XmlIgnore]
        public bool i8Specified
        {
            get { return i8SpecifiedField; }
            set { i8SpecifiedField = value; }
        }
        private string lpstrField = null;
        private string lpwstrField = null;
        private float r4Field = 0;
        private bool r4SpecifiedField = false;
        private double r8Field = 0;
        private bool r8SpecifiedField = false;

        [XmlElement]
        public string lpstr
        {
            get { return lpstrField; }
            set { lpstrField = value; }
        }
        [XmlElement]
        public string lpwstr
        {
            get { return lpwstrField; }
            set { lpwstrField = value; }
        }
        [XmlElement]
        public float r4
        {
            get { return r4Field; }
            set { r4Field = value; }
        }
        [XmlIgnore]
        public bool r4Specified
        {
            get { return r4SpecifiedField; }
            set { r4SpecifiedField = value; }
        }
        [XmlElement]
        public double r8
        {
            get { return r8Field; }
            set { r8Field = value; }
        }
        [XmlIgnore]
        public bool r8Specified
        {
            get { return r8SpecifiedField; }
            set { r8SpecifiedField = value; }
        }
    }


    [Serializable]
    [System.Diagnostics.DebuggerStepThrough]
    [System.ComponentModel.DesignerCategory("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]
    public partial class CT_Array
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private int lBoundsField;

        private int uBoundsField;

        private ST_ArrayBaseType baseTypeField;

    
        [XmlElement("bool", typeof(bool))]
        [XmlElement("bstr", typeof(string))]
        [XmlElement("cy", typeof(string))]
        [XmlElement("date", typeof(System.DateTime))]
        [XmlElement("decimal", typeof(decimal))]
        [XmlElement("error", typeof(string))]
        [XmlElement("i1", typeof(sbyte))]
        [XmlElement("i2", typeof(short))]
        [XmlElement("i4", typeof(int))]
        [XmlElement("int", typeof(int))]
        [XmlElement("r4", typeof(float))]
        [XmlElement("r8", typeof(double))]
        [XmlElement("ui1", typeof(byte))]
        [XmlElement("ui2", typeof(ushort))]
        [XmlElement("ui4", typeof(uint))]
        [XmlElement("uint", typeof(uint))]
        [XmlElement("variant", typeof(CT_Variant))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

    
        //[XmlElement("ItemsElementName")]
        [XmlIgnore]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

    
        [XmlAttribute]
        public int lBounds
        {
            get
            {
                return this.lBoundsField;
            }
            set
            {
                this.lBoundsField = value;
            }
        }

    
        [XmlAttribute]
        public int uBounds
        {
            get
            {
                return this.uBoundsField;
            }
            set
            {
                this.uBoundsField = value;
            }
        }

    
        [XmlAttribute]
        public ST_ArrayBaseType baseType
        {
            get
            {
                return this.baseTypeField;
            }
            set
            {
                this.baseTypeField = value;
            }
        }
    }
    [Serializable]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:bool")]
        @bool,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:bstr")]
        bstr,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:cy")]
        cy,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:date")]
        date,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:decimal")]
        @decimal,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:error")]
        error,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:i1")]
        i1,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:i2")]
        i2,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:i4")]
        i4,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:int")]
        @int,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:r4")]
        r4,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:r8")]
        r8,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:ui1")]
        ui1,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:ui2")]
        ui2,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:ui4")]
        ui4,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:uint")]
        @uint,

        [XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes:variant")]
        variant,
    }

    [Serializable]
    [System.Diagnostics.DebuggerStepThrough]
    [System.ComponentModel.DesignerCategory("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]

    public class CT_Vstream
    {

        private string versionField;

        private byte[] valueField;
        [XmlAttribute]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        [XmlTextAttribute(DataType = "base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    [XmlType(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes", IsNullable = true)]
    public class CT_Null
    {
    }
    [XmlType(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]
    [XmlRoot(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes", IsNullable = true)]
    public class CT_Empty
    {
    }
    [Serializable]
    [System.Diagnostics.DebuggerStepThrough]
    [System.ComponentModel.DesignerCategory("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]
    public class CT_Cf
    {

        private string formatField;

        private byte[] valueField;

        [XmlAttribute]
        public string format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        [XmlTextAttribute(DataType = "base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    [Serializable]
    [System.Diagnostics.DebuggerStepThrough]
    [System.ComponentModel.DesignerCategory("code")]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]
    public class CT_Vector
    {

        private ST_VectorBaseType baseTypeField;

        private uint sizeField;

        public CT_Vector()
        {
        }

        private bool @boolField=false;
        private bool @boolSpecifiedField = false;
        [XmlElement("bool")]
        public bool @bool
        {
            get { return @boolField; }
            set { @boolField = value; }
        }
        [XmlIgnore]
        public bool @boolSpecified
        {
            get { return @boolSpecifiedField; }
            set { @boolSpecifiedField = value; }
        }

        private string bstrField = null;
        [XmlElement]
        public string bstr
        {
            get { return bstrField; }
            set { bstrField = value; }
        }

        private CT_Cf cfField = null;
        private string clsidField = null;
        private string cyField = null;
        [XmlElement]
        public CT_Cf cf
        {
            get { return cfField; }
            set { cfField = value; }
        }
        [XmlElement]
        public string clsid
        {
            get { return clsidField; }
            set { clsidField = value; }
        }
        [XmlElement]
        public string cy
        {
            get { return cyField; }
            set { cyField = value; }
        }
        private DateTime dateField;
        private bool dateSpecifiedField = false;
        [XmlElement]
        public DateTime date
        {
            get { return dateField; }
            set { dateField = value; }
        }
        [XmlIgnore]
        public bool dateSpecified
        {
            get { return dateSpecifiedField; }
            set { dateSpecifiedField = value; }
        }
        private string errorField = null;
        [XmlElement]
        public string error
        {
            get { return errorField; }
            set { errorField = value; }
        }

        private DateTime filetimeField;
        private bool filetimeSpecifiedField = false;
        [XmlElement]
        public DateTime filetime
        {
            get { return filetimeField; }
            set { filetimeField = value; }
        }
        [XmlIgnore]
        public bool filetimeSpecified
        {
            get { return filetimeSpecifiedField; }
            set { filetimeSpecifiedField = value; }
        }
        private sbyte i1Field = 0;
        private bool i1SpecifiedField = false;
        private short i2Field = 0;
        private bool i2SpecifiedField = false;
        private int i4Field = 0;
        private bool i4SpecifiedField = false;
        private long i8Field = 0;
        private bool i8SpecifiedField = false;
        [XmlElement]
        public sbyte i1
        {
            get { return i1Field; }
            set { i1Field = value; }
        }
        [XmlIgnore]
        public bool i1Specified
        {
            get { return i1SpecifiedField; }
            set { i1SpecifiedField = value; }
        }
        [XmlElement]
        public short i2
        {
            get { return i2Field; }
            set { i2Field = value; }
        }
        [XmlIgnore]
        public bool i2Specified
        {
            get { return i2SpecifiedField; }
            set { i2SpecifiedField = value; }
        }
        [XmlElement]
        public int i4
        {
            get { return i4Field; }
            set { i4Field = value; }
        }
        [XmlIgnore]
        public bool i4Specified
        {
            get { return i4SpecifiedField; }
            set { i4SpecifiedField = value; }
        }
        [XmlElement]
        public long i8
        {
            get { return i8Field; }
            set { i8Field = value; }
        }
        [XmlIgnore]
        public bool i8Specified
        {
            get { return i8SpecifiedField; }
            set { i8SpecifiedField = value; }
        }
        private string lpstrField = null;
        private string lpwstrField = null;
        private float r4Field = 0;
        private bool r4SpecifiedField = false;
        private double r8Field = 0;
        private bool r8SpecifiedField = false;

        [XmlElement]
        public string lpstr
        {
            get { return lpstrField; }
            set { lpstrField = value; }
        }
        [XmlElement]
        public string lpwstr
        {
            get { return lpwstrField; }
            set { lpwstrField = value; }
        }
        [XmlElement]
        public float r4
        {
            get { return r4Field; }
            set { r4Field = value; }
        }
        [XmlIgnore]
        public bool r4Specified
        {
            get { return r4SpecifiedField; }
            set { r4SpecifiedField = value; }
        }
        [XmlElement]
        public double r8
        {
            get { return r8Field; }
            set { r8Field = value; }
        }
        [XmlIgnore]
        public bool r8Specified
        {
            get { return r8SpecifiedField; }
            set { r8SpecifiedField = value; }
        }
        private byte ui1Field = 0;
        private bool ui1SpecifiedField = false;
        private ushort ui2Field = 0;
        private bool ui2SpecifiedField = false;
        private uint ui4Field = 0;
        private bool ui4SpecifiedField = false;
        private ulong ui8Field = 0;
        private bool ui8SpecifiedField = false;

        [XmlElement]
        public byte ui1
        {
            get { return ui1Field; }
            set { ui1Field = value; }
        }
        [XmlIgnore]
        public bool ui1Specified
        {
            get { return ui1SpecifiedField; }
            set { ui1SpecifiedField=value; }
        }
        [XmlElement]
        public ushort ui2
        {
            get { return ui2Field; }
            set { ui2Field = value; }
        }
        [XmlIgnore]
        public bool ui2Specified
        {
            get { return ui2SpecifiedField; }
            set { ui2SpecifiedField = value; }
        }
        [XmlElement]
        public uint ui4
        {
            get { return ui4Field; }
            set { ui4Field = value; }
        }
        [XmlIgnore]
        public bool ui4Specified
        {
            get { return ui4SpecifiedField; }
            set { ui4SpecifiedField = value; }
        }
        [XmlElement]
        public ulong ui8
        {
            get { return ui8Field; }
            set { ui8Field = value; }
        }
        [XmlIgnore]
        public bool ui8Specified
        {
            get { return ui8SpecifiedField; }
            set { ui8SpecifiedField = value; }
        }

        private List<CT_Variant> variantsField;
        [XmlElement("variant")]
        public List<CT_Variant> variants
        {
            get { return variantsField; }
            set { variantsField = value; }
        }
        [XmlAttribute]
        public ST_VectorBaseType baseType
        {
            get
            {
                return this.baseTypeField;
            }
            set
            {
                this.baseTypeField = value;
            }
        }
        [XmlAttribute]
        public uint size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
    }

    [Serializable]
    [XmlType(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]
    public enum ST_VectorBaseType
    {

    
        variant,

    
        i1,

    
        i2,

    
        i4,

    
        i8,

    
        ui1,

    
        ui2,

    
        ui4,

    
        ui8,

    
        r4,

    
        r8,

    
        lpstr,

    
        lpwstr,

    
        bstr,

    
        date,

    
        filetime,

    
        @bool,

    
        cy,

    
        error,

    
        clsid,

    
        cf,
    }


}
