// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>schemas</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace NPOI.OpenXmlFormats
{
    using System.Xml.Serialization;
    using System.Collections.Generic;


    public class CT_Variant
    {

        private object itemField;

        private ItemChoiceType itemElementNameField;

        [XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        [XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]
    public partial class CT_Array
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private int lBoundsField;

        private int uBoundsField;

        private ST_ArrayBaseType baseTypeField;

        /// <remarks/>
        [XmlElementAttribute("bool", typeof(bool))]
        [XmlElementAttribute("bstr", typeof(string))]
        [XmlElementAttribute("cy", typeof(string))]
        [XmlElementAttribute("date", typeof(System.DateTime))]
        [XmlElementAttribute("decimal", typeof(decimal))]
        [XmlElementAttribute("error", typeof(string))]
        [XmlElementAttribute("i1", typeof(sbyte))]
        [XmlElementAttribute("i2", typeof(short))]
        [XmlElementAttribute("i4", typeof(int))]
        [XmlElementAttribute("int", typeof(int))]
        [XmlElementAttribute("r4", typeof(float))]
        [XmlElementAttribute("r8", typeof(double))]
        [XmlElementAttribute("ui1", typeof(byte))]
        [XmlElementAttribute("ui2", typeof(ushort))]
        [XmlElementAttribute("ui4", typeof(uint))]
        [XmlElementAttribute("uint", typeof(uint))]
        [XmlElementAttribute("variant", typeof(CT_Variant))]
        [XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("ItemsElementName")]
        [XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public int lBounds
        {
            get
            {
                return this.lBoundsField;
            }
            set
            {
                this.lBoundsField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public int uBounds
        {
            get
            {
                return this.uBoundsField;
            }
            set
            {
                this.uBoundsField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public ST_ArrayBaseType baseType
        {
            get
            {
                return this.baseTypeField;
            }
            set
            {
                this.baseTypeField = value;
            }
        }
    }
    [System.SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        @bool,

        /// <remarks/>
        bstr,

        /// <remarks/>
        cy,

        /// <remarks/>
        date,

        /// <remarks/>
        @decimal,

        /// <remarks/>
        error,

        /// <remarks/>
        i1,

        /// <remarks/>
        i2,

        /// <remarks/>
        i4,

        /// <remarks/>
        @int,

        /// <remarks/>
        r4,

        /// <remarks/>
        r8,

        /// <remarks/>
        ui1,

        /// <remarks/>
        ui2,

        /// <remarks/>
        ui4,

        /// <remarks/>
        @uint,

        /// <remarks/>
        variant,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]

    public class CT_Vstream
    {

        private string versionField;

        private byte[] valueField;
        [XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        [XmlTextAttribute(DataType = "base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public class CT_Null
    {
    }

    public class CT_Empty
    {
    }
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]
    public class CT_Cf
    {

        private string formatField;

        private byte[] valueField;

        [XmlAttributeAttribute()]
        public string format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        [XmlTextAttribute(DataType = "base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]
    public class CT_Vector
    {

        private List<object> itemsField;

        private List<ItemsChoiceType> itemsElementNameField;

        private ST_VectorBaseType baseTypeField;

        private uint sizeField;

        public CT_Vector()
        {
            this.itemsElementNameField = new List<ItemsChoiceType>();
            this.itemsField = new List<object>();
        }

        [XmlChoiceIdentifierAttribute("ItemsElementName")]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [XmlIgnoreAttribute()]
        public List<ItemsChoiceType> ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        public ST_VectorBaseType baseType
        {
            get
            {
                return this.baseTypeField;
            }
            set
            {
                this.baseTypeField = value;
            }
        }

        public uint size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [XmlTypeAttribute(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes")]
    public enum ST_VectorBaseType
    {

        /// <remarks/>
        variant,

        /// <remarks/>
        i1,

        /// <remarks/>
        i2,

        /// <remarks/>
        i4,

        /// <remarks/>
        i8,

        /// <remarks/>
        ui1,

        /// <remarks/>
        ui2,

        /// <remarks/>
        ui4,

        /// <remarks/>
        ui8,

        /// <remarks/>
        r4,

        /// <remarks/>
        r8,

        /// <remarks/>
        lpstr,

        /// <remarks/>
        lpwstr,

        /// <remarks/>
        bstr,

        /// <remarks/>
        date,

        /// <remarks/>
        filetime,

        /// <remarks/>
        @bool,

        /// <remarks/>
        cy,

        /// <remarks/>
        error,

        /// <remarks/>
        clsid,

        /// <remarks/>
        cf,
    }


}
